package:
  name: video_bibliotheek
  version: 0.1

source:
  git_url: https://github.com/vadella/video_library
  git_tag: test_tag

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 1
  include_recipe: False

requirements:
  build:
    - setuptools
    - python
  run:
    - python >=3.6
    - ffmpeg

test:
  imports:
    - video_bibliotheek

about:
  home: https://github.com/vadella/video_library

extra:
  final: true